using System.Collections.Generic;
using System.IO;
using UnityEngine;
using FallenAngel.Data;

namespace FallenAngel.Data
{
    /// <summary>
    /// 谱面加载器 - 支持从JSON文件加载自定义谱面
    /// </summary>
    public static class ChartLoader
    {
        /// <summary>
        /// 从Resources/Charts目录加载JSON谱面
        /// </summary>
        /// <param name="chartName">谱面文件名（不含.json和路径）</param>
        public static ChartData LoadFromResources(string chartName)
        {
            TextAsset jsonFile = Resources.Load<TextAsset>($"Charts/{chartName}");
            if (jsonFile == null)
            {
                Debug.LogError($"[ChartLoader] 无法找到谱面文件: Charts/{chartName}");
                return null;
            }

            return LoadFromJson(jsonFile.text);
        }

        /// <summary>
        /// 从JSON字符串解析谱面数据
        /// </summary>
        public static ChartData LoadFromJson(string jsonText)
        {
            try
            {
                ChartData chart = JsonUtility.FromJson<ChartData>(jsonText);
                if (chart == null)
                {
                    Debug.LogError("[ChartLoader] 谱面解析失败: JSON为空或格式错误");
                    return null;
                }

                chart.SortNotes();
                Debug.Log($"[ChartLoader] 成功加载谱面: {chart.metadata?.songName ?? "未知"}, 音符数: {chart.notes.Count}");
                return chart;
            }
            catch (System.Exception e)
            {
                Debug.LogError($"[ChartLoader] 谱面解析异常: {e.Message}");
                return null;
            }
        }

        /// <summary>
        /// 将谱面数据序列化为JSON字符串
        /// </summary>
        public static string SaveToJson(ChartData chart)
        {
            return JsonUtility.ToJson(chart, true);
        }

        /// <summary>
        /// 保存谱面为JSON文件（仅Editor模式可用）
        /// </summary>
        public static void SaveToFile(ChartData chart, string filePath)
        {
            string json = SaveToJson(chart);
#if UNITY_EDITOR
            File.WriteAllText(filePath, json);
            Debug.Log($"[ChartLoader] 谱面已保存至: {filePath}");
#else
            Debug.LogWarning("[ChartLoader] 运行时无法写入文件，请在Editor模式下使用");
#endif
        }

        /// <summary>
        /// 生成示例谱面（用于测试）
        /// </summary>
        public static ChartData GenerateDemoChart()
        {
            ChartData chart = new ChartData();
            chart.metadata = new ChartMetadata
            {
                songName = "堕落天使 - Demo",
                songArtist = "FallenAngel Team",
                chartAuthor = "AutoGenerated",
                difficulty = Difficulty.Normal,
                level = 7,
                bpm = 140f,
                offset = 0f,
                audioFileName = "demo_song",
                previewStartTime = 10f,
                previewDuration = 15f
            };

            // 生成一些简单的测试音符，按BPM生成
            float beatTime = 60f / chart.metadata.bpm;
            float currentTime = 2f; // 从2秒开始
            int longNoteIdCounter = 0;

            // 第一段：基础单键练习
            for (int i = 0; i < 16; i++)
            {
                chart.notes.Add(new NoteData(i % 4, currentTime, NoteType.Normal));
                currentTime += beatTime;
            }

            // 第二段：双键组合
            for (int i = 0; i < 8; i++)
            {
                chart.notes.Add(new NoteData(0, currentTime, NoteType.Normal));
                chart.notes.Add(new NoteData(3, currentTime, NoteType.Normal));
                currentTime += beatTime;

                chart.notes.Add(new NoteData(1, currentTime, NoteType.Normal));
                chart.notes.Add(new NoteData(2, currentTime, NoteType.Normal));
                currentTime += beatTime;
            }

            // 第三段：长按音符
            for (int i = 0; i < 4; i++)
            {
                float longDuration = beatTime * 2;
                int id = longNoteIdCounter++;
                chart.notes.Add(new NoteData(i, currentTime, NoteType.LongStart, longDuration, id));
                chart.notes.Add(new NoteData(i, currentTime + longDuration, NoteType.LongEnd, 0f, id));
                currentTime += beatTime * 3;
            }

            // 第四段：快速连打
            float sixteenthNote = beatTime * 0.25f;
            int[] pattern = { 0, 1, 2, 3, 3, 2, 1, 0, 0, 2, 1, 3, 3, 1, 2, 0 };
            for (int i = 0; i < pattern.Length; i++)
            {
                chart.notes.Add(new NoteData(pattern[i], currentTime, NoteType.Normal));
                currentTime += sixteenthNote;
            }

            // 结尾：同时长按
            float finalLongDuration = beatTime * 4;
            for (int l = 0; l < 4; l++)
            {
                int id = longNoteIdCounter++;
                chart.notes.Add(new NoteData(l, currentTime, NoteType.LongStart, finalLongDuration, id));
                chart.notes.Add(new NoteData(l, currentTime + finalLongDuration, NoteType.LongEnd, 0f, id));
            }

            chart.SortNotes();
            return chart;
        }
    }
}
